com:
  zfgoo:
    foo: bar
    database-platform: sql
    post[0]: Why Spring Boot
    post[1]: Why Spring Cloud
    posts[0]:
      title: Why Spring Boot
      content: It is perfect!
    posts[1]:
      title: Why Spring Cloud
      content: It is perfect too!
    blog:
      name: zfgcian@gmail.com
      title: Spring boot教程
      desc: ${com.zfgoo.blog.name}正在努力学习《${com.zfgoo.blog.title}》
      value: ${random.value}
      number: ${random.int}
      bignumber: ${random.long}
      random-num-in-10: ${random.int(10)}
      random-num-between-10-20: ${random.int[10,20]}
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fight?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/fight?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/bootdo?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: update
      show-sql: true
  ldap:
    urls: ldap://localhost:389
    base: dc=maxcrc,dc=com
    username: cn=Manager,dc=maxcrc,dc=com
    password: secret
  data:
    mongodb:
      uri: mongodb://localhost:27017/dnmogodbt
      option:
        min-connection-per-host: 20
        max-connection-per-host: 200