com:
  zfgoo:
    foo: bar
    database-platform: sql
    post[0]: Why Spring Boot
    post[1]: Why Spring Cloud
    posts[0]:
      title: Why Spring Boot
      content: It is perfect!
    posts[1]:
      title: Why Spring Cloud
      content: It is perfect too!
    blog:
      name: zfgcian@gmail.com
      title: Spring boot教程
      desc: ${com.zfgoo.blog.name}正在努力学习《${com.zfgoo.blog.title}》
      value: ${random.value}
      number: ${random.int}
      bignumber: ${random.long}
      random-num-in-10: ${random.int(10)}
      random-num-between-10-20: ${random.int[10,20]}
spring:
  profiles:
    active: dev
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/fight?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/fight?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    thirdly:
      jdbc-url: jdbc:mysql://localhost:3306/bootdo?useSSL=false
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #按字段名字建表
        hbm2ddl:
          auto: update
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #使用innodb引擎建表
  ldap:
    urls: ldap://localhost:389
    base: dc=maxcrc,dc=com
    username: cn=Manager,dc=maxcrc,dc=com
    password: secret
  data:
    mongodb:
      uri: mongodb://localhost:27017/dnmongodbt
      option:
        min-connection-per-host: 20
        max-connection-per-host: 200
  cache:
    type: redis
  ext:
    cache:
      name: countries
      redis:
        topic: cache
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 0ms
    max-wait: 5000
    max-active: 10
  flyway:
    locations: classpath:/db
    baselineOnMigrate: true