spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fight?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: update
      show-sql: true
  ldap:
    urls: ldap://localhost:389
    base: dc=maxcrc,dc=com
    username: cn=Manager,dc=maxcrc,dc=com
    password: secret
  data:
    mongodb:
      uri: mongodb://localhost:27017/dnmogodbt
      option:
        min-connection-per-host: 20
        max-connection-per-host: 200